### ISSUE TITLE
Concept Map

### ISSUE THREAD

**Issue by Deyrson** [Deyrson/SE-UMB-01#1]
## To-Do
- [ ] Leer el PDF del modulo 1 de la Pagina 1 a la 18
- [ ] Tomar apuntes y realizar un resumen de la unidad
- [ ] Realizar un mapa conceptual que explique detalladamente la temática explicada en el PDF

## Done
- [ ] Imagen en JPEG exportada desde CmapTools

> _Deadline: 08-08-16_ 
> _Keywords: logic programming, module 01, activity 01_
