### ISSUE TITLE
Set Theory Exercises

### ISSUE THREAD

**Issue by Deyrson** [Deyrson/SE-UMB-01#2]
## To-Do
- [ ] Leer PDF Modulo 1 pagina 18 en adelante.
- [ ] Ver video de apoyo sobre Matemáticas discreta
- [ ] La actividad se realizara en grupos asignados en el foro
- [ ] Solucionar a mano los ejercicios propuestos

## Done
- [ ] Documento scaneado con la solución de los ejercicios planteados

> _Deadline: 15-08-16_
> _Keywords: logic programming, module 01, activity 02_
