### ISSUE TITLE
PSeInt User Nanual

### ISSUE THREAD

**Issue by Deyrson** [Deyrson/SE-UMB-01#3]
## To-Do
- [ ] Leer el Modulo II
- [ ] Descargar programa PSeInt de http://pseint.sourceforge.net
- [ ] Ver video tutorial de apoyo
- [ ] Realizar en Word un documento de manual de usuario del uso de PSeInt.
- [ ] Ver Ejemplo de Manuales de usuario

## Done
- [ ] Documento en Word con el manual de usuario de PSeInt.

> _Deadline: 08-22-16_
> _Keywords: logic programming, module 02, activity 01_
