### ISSUE TITLE
PSeInt Exercises I

### ISSUE THREAD

**Issue by Deyrson** [Deyrson/SE-UMB-01#4]
## To-Do
- [ ] Trabajar en los grupos asignados para la actividad 2
- [ ] Estudiar temas del PDF Modulo II
- [ ] Tomar apuntes
- [ ] Presentar los dos programas y diagramas de flujo que se piden:

## Done 
- [ ] Programa que determine el tipo de triángulo según los valores leídos de los tres lados
- [ ] Programa que determine la existencia y la posición de un elemento en un arreglo de 10 posiciones
